# Generated by Django 5.2.7 on 2025-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('SUSPENSION', 'Suspension'), ('REGISTRATION', 'New Registration')], db_index=True, help_text='The type of event (e.g., withdrawal, new registration)', max_length=20)),
                ('source', models.CharField(choices=[('GIF', 'Chief Pharmaceutical Inspectorate'), ('URPL', 'Office for Registration of PL')], db_index=True, help_text='The source of the data (GIF or URPL)', max_length=10)),
                ('publication_date', models.DateField(db_index=True, help_text='Date the notice/decision was published or registration date')),
                ('decision_number', models.CharField(blank=True, help_text='Decision number (from GIF) or Permit number (from URPL)', max_length=255, null=True)),
                ('drug_name', models.CharField(db_index=True, help_text='Trade name of the medicinal product', max_length=255)),
                ('drug_strength', models.CharField(blank=True, help_text='Strength of the drug (e.g., 500 mg, 10 mg/ml)', max_length=100, null=True)),
                ('drug_form', models.CharField(blank=True, help_text='Pharmaceutical form (e.g., Tablets, Solution)', max_length=100, null=True)),
                ('marketing_authorisation_holder', models.CharField(help_text='The company responsible for the drug', max_length=255)),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='The batch (lot) number of the product', max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of the withdrawn/suspended batch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was added by the scraper')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record update')),
            ],
            options={
                'verbose_name': 'Drug Event',
                'verbose_name_plural': 'Drug Events',
                'ordering': ['-publication_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('decision_number', 'batch_number'), name='unique_decision_batch')],
            },
        ),
    ]
