# Generated by Django 4.2.11 on 2025-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu_leczniczego', models.CharField(db_index=True, help_text='Medicinal product name', max_length=500)),
                ('nazwa_powszechnie_stosowana', models.CharField(db_index=True, help_text='Common name / INN (International Nonproprietary Name)', max_length=500)),
                ('droga_podania_gatunek_tkanka_okres_karencji', models.CharField(blank=True, help_text='Route of administration, species, tissue, withdrawal period', max_length=200, null=True)),
                ('moc', models.CharField(blank=True, help_text='Strength/potency', max_length=200, null=True)),
                ('substancja_czynna', models.TextField(db_index=True, help_text='Active substance(s)')),
                ('numer_pozwolenia', models.CharField(blank=True, db_index=True, help_text='Authorization number', max_length=100, null=True)),
                ('podmiot_odpowiedzialny', models.CharField(blank=True, help_text='Marketing authorization holder', max_length=500, null=True)),
                ('nazwa_wytw_rcy', models.CharField(blank=True, help_text='Manufacturer name', max_length=500, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, help_text='Price', max_digits=10, null=True)),
                ('ilosc', models.IntegerField(blank=True, help_text='Quantity/amount', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['nazwa_produktu_leczniczego'],
                'indexes': [models.Index(fields=['nazwa_produktu_leczniczego'], name='pharmac_dru_nazwa_p_7b355d_idx'), models.Index(fields=['nazwa_powszechnie_stosowana'], name='pharmac_dru_nazwa_p_1c31f8_idx'), models.Index(fields=['substancja_czynna'], name='pharmac_dru_substan_19d27b_idx')],
            },
        ),
    ]
