# Generated by Django 4.2.11 on 2025-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='droga_podania_gatunek_tkanka_okres_karencji',
            field=models.TextField(blank=True, help_text='Route of administration, species, tissue, withdrawal period', null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='moc',
            field=models.TextField(blank=True, help_text='Strength/potency', null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='substancja_czynna',
            field=models.TextField(blank=True, db_index=True, help_text='Active substance(s)', null=True),
        ),
    ]
