# Generated by Django 4.2.11 on 2025-10-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.CharField(help_text='Numer pozycji (Lp.)', max_length=50)),
                ('nr_w_wykazie', models.CharField(db_index=True, help_text='Numer w wykazie (Nr w Wykazie)', max_length=100)),
                ('podstawa_wydania', models.TextField(help_text='Podstawa prawna wydania')),
                ('tytul_rozporzadzenia', models.TextField(blank=True, help_text='Tytuł rozporządzenia (oryginalny)')),
                ('przyczyny_rezygnacji', models.TextField(blank=True, help_text='Przyczyny rezygnacji z prac nad projektem')),
                ('planowany_termin_wydania', models.TextField(blank=True, help_text='Planowany termin wydania / Publikacja w Dz. U')),
                ('istota_rozwiazan', models.TextField(blank=True, help_text='Istota rozwiązań, które planuje się zawrzeć w projekcie')),
                ('osoba_odpowiedzialna', models.CharField(blank=True, help_text='Imię, nazwisko, stanowisko lub funkcja osoby odpowiedzialnej', max_length=500)),
                ('przyczyna_potrzeba', models.TextField(blank=True, help_text='Przyczyna i potrzeba wprowadzenia rozwiązań')),
                ('ai_tytul', models.CharField(blank=True, help_text='AI-generated title (concise and descriptive)', max_length=500, null=True)),
                ('ai_description', models.TextField(blank=True, help_text='AI-generated summary description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Regulation',
                'verbose_name_plural': 'Legal Regulations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nr_w_wykazie'], name='regulations_nr_w_wy_7f4135_idx'), models.Index(fields=['lp'], name='regulations_lp_4defed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='legalregulation',
            constraint=models.UniqueConstraint(fields=('nr_w_wykazie',), name='unique_regulation_number'),
        ),
    ]
