# Generated by Django 4.2.11 on 2025-10-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalregulation',
            name='planowany_termin_wydania_data',
            field=models.DateField(blank=True, help_text='Wygenerowana losowa data z kwartału planowanego terminu', null=True),
        ),
        migrations.AlterField(
            model_name='legalregulation',
            name='planowany_termin_wydania',
            field=models.TextField(blank=True, help_text='Planowany termin wydania / Publikacja w Dz. U (tekst)'),
        ),
    ]
