services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharma-landing
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    networks:
      - pharma-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 11s
      retries: 3
      start_period: 40s

networks:
  pharma-network:
    driver: bridge

