# Generated by Django 4.2.11 on 2025-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('title_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_translated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Medical News',
                'verbose_name_plural': 'Medical News',
                'ordering': ['-published_at'],
            },
        ),
    ]
